security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: database_users
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cart, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }
